apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-service-1
  namespace: default
  labels:
    app: spring-service-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-service-1
  template:
    metadata:
      labels:
        app: spring-service-1
    spec:
      containers:
      - name: spring-service-1
        image: choho97/stackup/spring_1:latest
        ports:
        - containerPort: 8080
