apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-account
  namespace: default
  labels:
    app: spring-account
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-account
  template:
    metadata:
      labels:
        app: spring-account
    spec:
      containers:
      - name: spring-account
        image: choho97/stackup-account:45
        ports:
        - containerPort: 8080
