apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackup-frontend
  labels:
    app: stackup-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stackup-frontend
  template:
    metadata:
      labels:
        app: stackup-frontend
    spec:
      containers:
      - name: stackup-frontend
        image: choho97/stackup-frontend:latest # Jenkins에서 업데이트된 이미지 태그가 반영됩니다.
        ports:
        - containerPort: 80
