apiVersion: v1
kind: Service
metadata:
  name: stackup-frontend-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: stackup-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
