apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80        # 외부에서 접근할 포트
      targetPort: 3000 # 컨테이너 내부의 React 서버 포트
  selector:
    app: react-app
