apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: default
spec:
  selector:
    app: react-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP  # 내부에서만 접근하려면 ClusterIP, 외부에서 접근하려면 NodePort나 LoadBalancer 사용
