apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-board
  namespace: default
  labels:
    app: spring-board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-board
  template:
    metadata:
      labels:
        app: spring-board
    spec:
      containers:
      - name: spring-board
        image: choho97/stackup-board:66
        ports:
        - containerPort: 8080
