apiVersion: v1
kind: Service
metadata:
  name: spring-board
  namespace: default
  labels:
    app: spring-board
spec:
  selector:
    app: spring-board
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: ClusterIP
