apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-user
  namespace: default
  labels:
    app: spring-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-user
  template:
    metadata:
      labels:
        app: spring-user
    spec:
      containers:
      - name: spring-user
        image: choho97/stackup-user:79
        envFrom:
        - configMapRef:
            name: my-test-config
        ports:
        - containerPort: 8080
