apiVersion: v1
kind: Service
metadata:
  name: spring-service-1
  labels:
    app: spring-service-1
spec:
  selector:
    app: spring-service-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
