apiVersion: v1
kind: Service
metadata:
  name: spring-user
  namespace: default
  labels:
    app: spring-user
spec:
  selector:
    app: spring-user
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
