apiVersion: v1
kind: Service
metadata:
  name: spring-account
  namespace: default
  labels:
    app: spring-account
spec:
  selector:
    app: spring-account
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
  type: ClusterIP
