apiVersion: v1
kind: Service
metadata:
  name: spring-service-2
  namespace: default
  labels:
    app: spring-service-2
spec:
  selector:
    app: spring-service-2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
