apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80          # 외부에서 접근할 포트
      targetPort: 5000   # Flask 애플리케이션이 사용하는 내부 포트
  selector:
    app: flask-app       # app 라벨과 일치하도록 수정 (flask-app)
